[package]
name = "star_frame_idl"
version = "0.1.0"
edition = "2021"
publish = ["star-atlas"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
verifier = ["anyhow"]

[dependencies]
bincode = { version = "1.3.3", features = ["i128"] }
derivative = "2.2.0"
derive_more = "0.99.17"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
solana-sdk = { workspace = true }

# verifier
anyhow = { version = "1.0.75", optional = true }

[dev-dependencies]
anyhow = "1.0.75"
rand = "0.8.5"
