[package]
name = "pod_vec"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
bytemuck.workspace = true
num-traits.workspace = true
