name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on:
      group: sa-runners
    permissions:
      pull-requests: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4
