name: build-lint-test
permissions:
  contents: read
  pull-requests: write

on:
  merge_group:
  pull_request:
    branches: ['main']
    types: [synchronize, opened, reopened]

jobs:
  build:
    runs-on:
      group: sa-runners
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_shipyard
        with:
          ssh-private-key: ${{ secrets.PRIVATE_REPO_SSH }}
          private-repo-token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --all-features

  lint:
    runs-on:
      group: sa-runners
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_shipyard
        with:
          ssh-private-key: ${{ secrets.PRIVATE_REPO_SSH }}
          private-repo-token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo clippy --all-targets --all-features

  fmt:
    runs-on:
      group: sa-runners
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_shipyard
        with:
          ssh-private-key: ${{ secrets.PRIVATE_REPO_SSH }}
          private-repo-token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: 'false'
      - run: cargo fmt --check

  test:
    runs-on:
      group: sa-runners
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_shipyard
        with:
          ssh-private-key: ${{ secrets.PRIVATE_REPO_SSH }}
          private-repo-token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --all-features

  miri:
    runs-on:
      group: sa-runners
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_shipyard
        with:
          ssh-private-key: ${{ secrets.PRIVATE_REPO_SSH }}
          private-repo-token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 'nightly'
          components: 'miri'
      - name: Set up miri
        run: cargo +nightly miri setup
      - run: 'MIRIFLAGS="-Zmiri-tree-borrows" cargo +nightly miri test --features "test_helpers" unsize::'
        working-directory: star_frame
